Models/ErrorViewModel.cs
namespace TransectionTest1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TranDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace TransectionTest1.Models
{
    public class TranDbContext:DbContext
    {
        public TranDbContext(DbContextOptions<TranDbContext> options) : base(options)
        {

        }

        public DbSet<Transaction23cs> TransactionsGP { get; set; }
    }
}

Models/Transaction23cs.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace TransectionTest1.Models
{
    public class Transaction23cs
    {
        [Key]
        public int TransactionId { get; set; }

        [Column(TypeName = "nvarchar(12)")]
        [DisplayName("Account Number")]
        [Required(ErrorMessage = "This Field is required")]
        [MaxLength(12, ErrorMessage = "Maximum 12 digits only")]
        public string AccountNumber { get; set; }

        [Column(TypeName = "nvarchar(100)")]
        [DisplayName("Beneficiary Name")]
        [Required(ErrorMessage = "This Field is required")]
        public string BeneficiaryName { get; set; }

        [Column(TypeName = "nvarchar(100)")]
        [DisplayName("Bank Name")]
        [Required(ErrorMessage = "This Field is required")]
        public string BankName { get; set; }

        [Column(TypeName = "nvarchar(11)")]
        [DisplayName("SWIFT Code")]
        [Required(ErrorMessage = "This Field is required")]
        [MaxLength(11, ErrorMessage = "Maximum 11 digits only")]
        public string SWIFTCode { get; set; }

        [Required(ErrorMessage = "This Field is required")]
        public int Amount { get; set; }

        [DisplayFormat(DataFormatString ="{0:MMM-dd-yy}")]
        public DateTime Date { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TransectionTest1.Models;

namespace TransectionTest1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/Transaction23csController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TransectionTest1.Models;

namespace TransectionTest1.Controllers
{
    public class Transaction23csController : Controller
    {
        private readonly TranDbContext _context;

        public Transaction23csController(TranDbContext context)
        {
            _context = context;
        }

        // GET: Transaction23cs
        public async Task<IActionResult> Index()
        {
              return _context.TransactionsGP != null ? 
                          View(await _context.TransactionsGP.ToListAsync()) :
                          Problem("Entity set 'TranDbContext.TransactionsGP'  is null.");
        }

      

        // GET: Transaction23cs/Create
        public IActionResult AddOrEdit(int id=0)
        {
            if(id == 0) 
            {
                return View(new Transaction23cs());
            }
            else 
            {
                return View(_context.TransactionsGP.Find(id));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("TransactionId,AccountNumber,BeneficiaryName,BankName,SWIFTCode,Amount,Date")] Transaction23cs transaction23cs)
        {
            if (ModelState.IsValid)
            {
                if (transaction23cs.TransactionId == 0)
                {
                    transaction23cs.Date = DateTime.Now;
                    _context.Add(transaction23cs);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
               else
                {
                    _context.Update(transaction23cs);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                    
                
               
            }
            return View(transaction23cs);
        }

        // GET: Transaction23cs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TransactionsGP == null)
            {
                return NotFound();
            }

            var transaction23cs = await _context.TransactionsGP
                .FirstOrDefaultAsync(m => m.TransactionId == id);
            if (transaction23cs == null)
            {
                return NotFound();
            }

            return View(transaction23cs);
        }

        // POST: Transaction23cs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TransactionsGP == null)
            {
                return Problem("Entity set 'TranDbContext.TransactionsGP'  is null.");
            }
            var transaction23cs = await _context.TransactionsGP.FindAsync(id);
            if (transaction23cs != null)
            {
                _context.TransactionsGP.Remove(transaction23cs);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AboutMe(int? id) 
        { 
            return View();
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BankTransaction</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/BankTransaction.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Transaction23cs" asp-action="Index">BankTransaction</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction23cs" asp-action="AboutMe">About me </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="height:80vh">
        <main role="main" class="pb-3">
            <div class="col-md-8 offset-md-2">
                @RenderBody()
            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BankTransaction - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Transaction23cs/AboutMe.cshtml
@{
    ViewData["Title"] = "About Me";
}
<h1>@ViewData["Title"]</h1>

<p>
    🚀 Hey, I'm Rishikesh Nandurkar! 👨‍💻 I thrive on coding magic, recently conjuring up a sleek CRUD system in 
    .NET MVC Core with Entity Framework Code First. Dive into the coding journey with me! 
    Let's chat tech, share ideas, or explore opportunities at <a href="mailto:nrnnandurkar@gmail.com" target="_blank">nrnnandurkar@gmail.com</a>
</p>

Views/Transaction23cs/AddOrEdit.cshtml
@model TransectionTest1.Models.Transaction23cs

@{
    ViewData["Title"] = "Create";
}




<hr />
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h1>Transaction</h1>
        @*autocomplet off helps to hide previous entered data hide*@
        <form asp-action="AddOrEdit" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TransactionId"/>
            <input type="hidden" asp-for="Date"/>
            <div class="form-group">
                <label asp-for="AccountNumber" class="control-label"></label>
                <input asp-for="AccountNumber" class="form-control" type="number" min="0"/>
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BeneficiaryName" class="control-label"></label>
                <input asp-for="BeneficiaryName" class="form-control" />
                <span asp-validation-for="BeneficiaryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <input asp-for="BankName" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>
            <div class="row">
                <div class=" col-md-6">
                    <div class="form-group">
                        <label asp-for="SWIFTCode" class="control-label"></label>
                        <input asp-for="SWIFTCode" class="form-control" />
                        <span asp-validation-for="SWIFTCode" class="text-danger"></span>
                    </div>
                </div>
                <div class=" col-md-6">
                    <div class="form-group">
                        <label asp-for="Amount" class="control-label"></label>
                        <input asp-for="Amount" class="form-control" min="0" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row mt-2">
                <div class=" col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Submit" class="btn btn-primary w-100" />
                    </div>
                </div>
                <div class=" col-md-6">
                    <div>
                        <a asp-action="Index" class="btn btn-secondary w-100">View All</a>
                    </div>
                </div>
            </div>


        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Transaction23cs/Delete.cshtml
@model TransectionTest1.Models.Transaction23cs

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction23cs</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BeneficiaryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BeneficiaryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SWIFTCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SWIFTCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TransactionId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Transaction23cs/Index.cshtml
@model IEnumerable<TransectionTest1.Models.Transaction23cs>


@{
    ViewData["Title"] = "Index";
}

<h3>Passbook</h3>

<p>
   
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AccountNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BeneficiaryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                <a asp-action="AddOrEdit" class="btn btn-sm btn-success" ><i class="fa-solid fa-plus"></i>New</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AccountNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BeneficiaryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    <a asp-action="AddOrEdit" asp-route-id="@item.TransactionId" class="btn btn-danger">
                        <i class="fa-solid fa-pen-to-square"></i>
                        </a>

                    <form asp-action="Delete" asp-route-id="@item.TransactionId">
                           <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete this record')">
                            <i class="far fa-trash-alt"></i>
                           </button>
                        </form>
                    
                </td>
            </tr>
        }
    </tbody>
</table>